channels:
  - conda-forge
dependencies:
  - numpy=1.24.1
  - ipykernel=6.26.0
  - ipython=8.18.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.0
  - pandas=1.5.2
  - python=3.9.17
  - python_abi=3.9
  - pyyaml=5.4.1
  - pip=24.3.1
  - rdkit=2024.9.2
  - rich=12.6.0
  - typing-extensions>=4.14.1
  - dask=2024.2.1
  - matplotlib=3.9.2
  - pip:
    - torch==2.8.0
    - torchtext==0.18.0
    - torchvision==0.23.0
    - torchaudio==2.8.0
    - accelerate==0.34.2
    - ncbi-genome-download==0.3.3
    - joblib==1.4.2
    - cellxgene_census==1.15.0
    - rich==13.8.0
    - transformers==4.45.1
    - scgpt==0.2.4
    - rdchiral==1.1.0
    - loompy==3.0.8
    - sentencepiece==0.2.0
    - tensorboardX==2.6.2.2
    - safetensors==0.4.3
    - biopython==1.85
    - pysam==0.23.3
    - pyfaidx==0.9.0.1
    - fcd==1.2.2
    - guacamol==0.5.5
    - deepchem==2.8.0
    - wandb>=0.18.0,<0.19
    - iniconfig==2.1.0
    - pytest==8.4.2
