data_preparation:
  # Path to save the untokenized OrganiX13 dataset once is downloaded and processed by the script
  organix13_dataset: "src/compounds/dataset/organix13"

  # Path to save the processed and tokenized dataset
  save_path: "outputs/organix13_tokenized.parquet"

  # Path to the vocabulary
  vocab_path: "assets/molecules/vocab.txt"

  # Max length of the tokenized sequences
  max_length: 256
