data_preparation:
  # Output directory where the preparation will be made
  output_dir: "/nasa/datasets/riken/projects/fundamental_models_202407/refseq"

  # Num of parallel worker to use, note that for download the worker are capped to 3
  num_worker: 16

  max_lines_per_file: 10000

  # Size of the vocabulary of the BPE tokenizer
  vocab_size: 4096
